#!/bin/bash
# Quick Reference: Jenkins Testing Job Setup

echo "📖 Jenkins Testing Job - Quick Reference"
echo "========================================"
echo ""

# Step 1: Get Webhook URL
echo "📍 STEP 1: Get Your Webhook URL"
echo "================================"
echo "Run this command:"
echo "  ./get-webhook-url.sh http://your-jenkins-url:8080"
echo ""
echo "Or with default localhost:"
echo "  ./get-webhook-url.sh"
echo ""
echo "Will show you:"
echo "  ✓ Webhook URL for GitHub"
echo "  ✓ Job trigger URL"
echo "  ✓ Console output URL"
echo ""

# Step 2: Setup GitHub Webhook
echo "🔗 STEP 2: Setup GitHub Webhook"
echo "================================"
echo "1. Go to: https://github.com/bhandhuvistu/my-testing-/settings/hooks"
echo "2. Add webhook with:"
echo "   - Payload URL: http://your-jenkins-url:8080/github-webhook/"
echo "   - Content type: application/json"
echo "   - Events: Push events, Pull requests"
echo ""

# Step 3: Create Jenkins Job
echo "🚀 STEP 3: Create Jenkins Testing Job"
echo "====================================="
echo "Option A: Manual Setup"
echo "  1. Jenkins Dashboard → New Item"
echo "  2. Name: testing-job"
echo "  3. Type: Pipeline"
echo "  4. Pipeline → Script from SCM"
echo "  5. SCM: Git"
echo "  6. Repository: https://github.com/bhandhuvistu/my-testing-.git"
echo "  7. Script Path: .jenkins/testing-job"
echo "  8. Save"
echo ""
echo "Option B: Using Jenkins File"
echo "  Copy .jenkins/testing-job to your Jenkins job"
echo ""

# Step 4: Test
echo "🧪 STEP 4: Test the Everything"
echo "==============================="
echo "Manual Trigger:"
echo "  ./trigger-testing-job.sh http://your-jenkins-url:8080 testing-job"
echo ""
echo "With Parameters:"
echo "  ./trigger-testing-job.sh http://your-jenkins-url:8080 testing-job main all true"
echo ""
echo "Parameters:"
echo "  arg1: Jenkins URL (default: http://localhost:8080)"
echo "  arg2: Job name (default: testing-job)"
echo "  arg3: Git branch (default: main)"
echo "  arg4: Test type (default: all) - unit/integration/all"
echo "  arg5: Generate report (default: true) - true/false"
echo ""

# Step 5: View Results
echo "📊 STEP 5: View Test Results"
echo "============================"
echo "In Jenkins:"
echo "  Go to: http://your-jenkins-url:8080/job/testing-job/"
echo "  Click latest build number"
echo "  View:"
echo "    - Test Result"
echo "    - Console Output"
echo "    - Artifacts (if generated)"
echo ""

echo ""
echo "💡 QUICK COMMANDS"
echo "================="
echo ""

echo "Get webhook URL:"
echo "  ./get-webhook-url.sh"
echo ""

echo "Trigger test job:"
echo "  ./trigger-testing-job.sh"
echo ""

echo "Push to GitHub (auto-triggers tests):"
echo "  git add ."
echo "  git commit -m 'Update code'"
echo "  git push origin main"
echo ""

echo "View test results via curl:"
echo "  curl http://localhost:8080/job/testing-job/lastBuild/consoleText"
echo ""

echo "Get full build info:"
echo "  curl http://localhost:8080/job/testing-job/lastBuild/api/json"
echo ""

echo ""
echo "📚 DETAILED GUIDES"
echo "=================="
echo ""
echo "See:"
echo "  - JENKINS_TESTING_GUIDE.md (Complete setup guide)"
echo "  - .jenkins/testing-job (Testing pipeline definition)"
echo "  - URL_PATHS.md (Find application URLs)"
echo ""
